services:
  db:
    image: mysql:8.0
    container_name: ecommerce_db_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ecommerce_mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: ecommerce_web_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - mysql_data:
      - static_volume:
      - media_volume:
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db

volumes:
  mysql_data:
  static_volume:
  media_volume:
