# Generated by Django 5.1 on 2025-07-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolesbase",
            options={"verbose_name": "Rol", "verbose_name_plural": "Roles"},
        ),
    ]
