# Generated by Django 5.1 on 2025-07-28 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_reparto", "En reparto"),
                            ("completado", "Completado"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("nombre_producto", models.CharField(default="", max_length=150)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                ("unidad", models.CharField(blank=True, max_length=50)),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("gondola", models.CharField(blank=True, max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.producto",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ordenes.orden",
                    ),
                ),
            ],
        ),
    ]
