# Generated by Django 5.1 on 2025-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_reparto", "En reparto"),
                    ("completado", "Completado"),
                ],
                default="pendiente",
                max_length=50,
                null=True,
            ),
        ),
    ]
